# Generated by Django 4.0.10 on 2023-03-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_users_playlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='users_playlist_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='Playlist Id'),
        ),
    ]
